// Package manifest generates AD-26's third-party licence manifest
// (AC19, AC20): every module in each of the repo's three Go module
// graphs, with a resolved licence, labelled with the module it serves
// and whether that module is shipped or build-time-only.
package manifest

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/panitw/folio/lint/internal/licence"
)

// servedModule is one of the repo's three real Go modules, and whether
// what it produces is shipped to consumers or exists only to build/test
// the repo (D-1.3.9's shipped/build-time-only label — it does not soften
// AC18's uniform ban; it exists so a future "this copyleft tool is only
// used at build time" argument has to be made explicitly, to the owner).
type servedModule struct {
	dirName   string // relative to repo root
	name      string // as it appears in the manifest's "serves" column
	shippedBy string // "shipped" or "build-time-only"
}

// servedModules is deliberately not derived from a directory listing:
// AD-26 binds all three named modules explicitly (D-1.3.9), and a
// silently-discovered fourth module must not silently join the ban's
// scope without a developer noticing it in a diff.
var servedModules = []servedModule{
	{dirName: "folio-go", name: "folio-go", shippedBy: "shipped"},
	{dirName: "hashmatrix", name: "hashmatrix", shippedBy: "build-time-only"},
	{dirName: "lint", name: "lint", shippedBy: "build-time-only"},
}

// Row is one manifest entry: a resolved dependency, the licence it
// classified as, which repo module it serves, and whether that module
// ships to consumers.
type Row struct {
	Module    string
	Version   string
	Licence   string
	Serves    string
	ShippedBy string
}

// Generate resolves all three of the repo's Go module graphs and
// returns the manifest as a sorted set of rows (AC19). A module whose
// licence cannot be resolved is still included, with Licence set to
// "UNRESOLVED" — Generate itself never fails the build; that is AC18's
// job (rules.ScanLicenceGraph), kept as a separate concern so the
// manifest can always be regenerated and inspected even while red.
func Generate(repoRoot string) ([]Row, error) {
	var rows []Row
	for _, sm := range servedModules {
		modDir := filepath.Join(repoRoot, sm.dirName)
		modules, err := licence.ResolveGraph(modDir)
		if err != nil {
			return nil, fmt.Errorf("resolve %s graph: %w", sm.dirName, err)
		}
		for _, m := range modules {
			row := Row{Module: m.Path, Version: m.Version, Serves: sm.name, ShippedBy: sm.shippedBy}
			text, ok := licence.ReadLicenceText(m.Dir)
			if !ok {
				row.Licence = "UNRESOLVED"
			} else if _, spdx := licence.ClassifyLicenceText(text); spdx != "" {
				row.Licence = spdx
			} else {
				row.Licence = "UNRESOLVED"
			}
			rows = append(rows, row)
		}
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].Serves != rows[j].Serves {
			return rows[i].Serves < rows[j].Serves
		}
		return rows[i].Module < rows[j].Module
	})
	return rows, nil
}

// Render formats rows as the committed Markdown manifest (AC19: "a
// committed, reviewable file"). The header states explicitly that a
// checker covering its own dependency is correct, not a bootstrap
// problem (AC20, D-1.3.6, D-1.3.9), so nobody reading it mistakes
// lint's own row for a mistake.
func Render(rows []Row) string {
	var b strings.Builder
	b.WriteString("# Third-party licence manifest\n\n")
	b.WriteString("Generated by `lint/internal/manifest` (AC19, AD-26). Every module in the\n")
	b.WriteString("resolved dependency graph of each of this repository's three Go modules —\n")
	b.WriteString("`folio-go`, `hashmatrix` and `lint` — appears below with its resolved\n")
	b.WriteString("licence, which module it serves, and whether that module ships to\n")
	b.WriteString("consumers or exists only to build/test the repo. An unresolved or\n")
	b.WriteString("unrecognised licence fails the build (AC19) rather than appearing here\n")
	b.WriteString("silently; a forbidden licence (GPL, LGPL, AGPL, SSPL, or a commercial\n")
	b.WriteString("EULA) fails the build uniformly across all three modules, with no\n")
	b.WriteString("build-time-only relaxation (AC18, D-1.3.9).\n\n")
	b.WriteString("**`lint`'s own dependency, if any, is covered by this same table below.\n")
	b.WriteString("A checker covering its own dependency is correct, not a bootstrap\n")
	b.WriteString("problem** (AC20, D-1.3.6, D-1.3.9) — it must not be \"fixed\" by excluding\n")
	b.WriteString("lint's own module: AD-26 binds all, and a licence manifest that omits the\n")
	b.WriteString("one module doing the checking is exactly the self-exemption this rule\n")
	b.WriteString("exists to prevent.\n\n")
	if len(rows) == 0 {
		b.WriteString("_No external dependencies exist in any of the three module graphs at\n")
		b.WriteString("this commit (F-8). This table is not empty theatre: it is complete for\n")
		b.WriteString("what exists, and AC19 makes an unresolvable licence a build failure so it\n")
		b.WriteString("stays complete as the graph grows._\n")
		return b.String()
	}
	b.WriteString("| Module | Version | Licence | Serves | Shipped / build-time-only |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", r.Module, r.Version, r.Licence, r.Serves, r.ShippedBy)
	}
	return b.String()
}
