import { expect, test } from '@playwright/test'

test('the five closed palette choices can begin an accessible local placement', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Place Text' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Place Image' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Place Table' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Place Line' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Place Rectangle' })).toBeVisible()
  await page.getByRole('button', { name: 'Place Text' }).click()
  await page.getByLabel('Content').press('Enter')
  await expect(page.getByLabel(/text component e/)).toBeVisible()
})

test('a palette pointer drag drops, selects, moves, resizes, and deletes through the local engine', async ({ page }) => {
  await page.goto('/')
  const palette = page.getByRole('button', { name: 'Place Rectangle' })
  const content = page.getByLabel('Content')
  const paletteBox = await palette.boundingBox()
  const contentBox = await content.boundingBox()
  if (!paletteBox || !contentBox) throw new Error('canvas placement targets were not painted')
  await page.mouse.move(paletteBox.x + paletteBox.width / 2, paletteBox.y + paletteBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(contentBox.x + 120, contentBox.y + 120)
  await page.mouse.up()

  const component = page.getByLabel(/rect component e/)
  await expect(component).toBeVisible()
  const box = await component.boundingBox()
  if (!box) throw new Error('created component was not painted')
  await page.mouse.move(box.x + 8, box.y + 8)
  await page.mouse.down()
  await page.mouse.move(box.x + 20, box.y + 14)
  await page.mouse.up()
  await expect(page.getByRole('status')).toContainText('Unsaved local changes')

  const handle = page.getByRole('button', { name: /Resize e/ })
  await expect(handle).toBeVisible()
  const handleBox = await handle.boundingBox()
  if (!handleBox) throw new Error('resize hit target was not painted')
  await page.mouse.move(handleBox.x + handleBox.width / 2, handleBox.y + handleBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(handleBox.x + handleBox.width / 2 + 12, handleBox.y + handleBox.height / 2 + 8)
  await page.mouse.up()

  await component.focus()
  await page.keyboard.press('Delete')
  await expect(component).toHaveCount(0)
})
